# Generated by Django 4.2.5 on 2023-09-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='you_tube',
            field=models.URLField(default='Multimedia'),
            preserve_default=False,
        ),
    ]
