# Generated by Django 4.2.5 on 2023-09-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_multimedia_you_tube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='you_tube',
        ),
    ]
