# Generated by Django 4.2.5 on 2023-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='url',
            field=models.URLField(default='Multimedia'),
            preserve_default=False,
        ),
    ]
